name: Running basic commands

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running Hello World
        run: echo "Hello World"
        shell: bash
  goodbye_world:
    runs-on: ubuntu-latest
    steps:
      - name: Running Goodbye World
        run: echo "Goodbye World"
        shell: bash
