name: Comment on issues using Community Actions

on: 
  issues:
    types: [opened]

jobs:
  comments-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: dumping github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
